version: '3.3'

services:
    db:
        image: mysql
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: defDB
            #MYSQL_USER: defUSER                <-- uncomment if you want to enable the normal user
            #MYSQL_PASSWORD: defPASSWD          <-- uncomment if you want to enable the password for the normal user
    php42:
        depends_on:
            - db
        links:
            - db
        image: arizzell/php42:php-apache
        volumes:
            - DIR:/var/www/html                #<-- replace DIR with the folder of your project (usually where you have the index.php or index.html file)
            #Ex. In my case will be:
            #/Users/arizzell/Documents/www:/var/www/html
        ports:
            - 80:80
volumes:
    dbdata:
